import { z } from 'zod';

/**
 * Phase 7 — a referral program, non-custodial by construction: see
 * docs/REFERRALS.md. Nothing here ever moves funds automatically. The platform fee wallet
 * still receives 100% of every trade's fee on-chain, exactly as before this existed — a
 * referrer's earned share is tracked and displayed here purely as *database accounting*
 * of how much of that already-collected fee is earmarked for them, which the operator
 * pays out manually and periodically (see docs/REFERRALS.md#payouts), the same
 * "track precisely, sweep by hand" pattern already used for consolidating mixed-token
 * platform fees. No new custody risk is introduced.
 */

/** The referrer's cut of the platform fee generated by trades from users they referred —
 *  out of Kamby's own existing fee, never an extra charge added on top of the trader. 20%
 *  is a starting number, not load-bearing anywhere outside this constant. */
export const REFERRAL_SHARE_BPS = 2000;

/**
 * Referral earnings are computed and shown in USDC only — see
 * docs/REFERRALS.md#currency-scope. A referred user's trade only contributes when its
 * platform fee was collected through the guaranteed-USDC-fee flow (see
 * docs/TRADING.md#guaranteed-usdc-fees); a trade whose fee rode a non-USDC-quoted market's
 * aggregator-embedded cut contributes nothing to this total. Summing raw fee amounts
 * across trades denominated in different tokens would be meaningless — silently treating a
 * DEGEN-denominated fee as if it were the same unit as a USDC one — so this scope
 * limitation is deliberate honesty, not an oversight, and narrows as more markets move
 * onto the guaranteed-USDC flow.
 */
export const ReferralSummarySchema = z.object({
  referralCode: z.string(),
  /** The API deliberately returns only the bare code, not a full URL — it doesn't know
   *  which of Kamby's own domains/hosts the caller is actually on. Building the shareable
   *  link (this code + `window.location.origin`) is the frontend's job — see
   *  apps/web/components/referrals. */
  referredCount: z.number().int().min(0),
  /** Raw USDC units (6 decimals), as a string — never a JS number, same rule as every
   *  other on-chain amount in this codebase. */
  earnedUsdcAmountRaw: z.string(),
  earnedUsdcAmountFormatted: z.string(),
});
export type ReferralSummaryDto = z.infer<typeof ReferralSummarySchema>;
